const express=require("express");const http=require("http");const {Server}=require("socket.io");const crypto=require("crypto");
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:true}});app.use(express.static("public"));
const rooms=new Map(),MIN=4,MAX=16,DEFAULT={night:35,day:90,vote:30};
const makeCode=()=>{let c;do c=crypto.randomBytes(3).toString("hex").toUpperCase();while(rooms.has(c));return c};
const alive=r=>[...r.players.values()].filter(p=>p.alive),mafia=r=>alive(r).filter(p=>p.role==="mafia");
function assignRoles(players){const a=[...players],r=Array(a.length>=8?2:1).fill("mafia");if(a.length>=4)r.push("oldman");if(a.length>=5)r.push("doctor");while(r.length<a.length)r.push("citizen");for(let i=r.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}a.forEach((p,i)=>{p.role=r[i];p.alive=true;p.usedOldman=false;p.nightDone=false})}
function winner(r){const a=alive(r),m=a.filter(p=>p.role==="mafia").length;return m===0?"citizens":m>=a.length-m?"mafia":null}
function publicRoom(r){return{code:r.code,hostId:r.hostId,started:r.started,phase:r.phase,maxPlayers:r.maxPlayers,timerEndsAt:r.timerEndsAt,settings:r.settings,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,alive:p.alive}))}}
function emitRoom(r){io.to(r.code).emit("room:update",publicRoom(r))}function clearTimer(r){if(r.timer)clearTimeout(r.timer);r.timer=null}
function startTimer(r,phase,seconds,fn){clearTimer(r);r.phase=phase;r.timerEndsAt=Date.now()+seconds*1000;io.to(r.code).emit("game:phase",{phase,endsAt:r.timerEndsAt});emitRoom(r);r.timer=setTimeout(fn,seconds*1000)}
function endGame(r,w){clearTimer(r);r.phase="ended";r.timerEndsAt=null;io.to(r.code).emit("game:ended",{winner:w,players:[...r.players.values()].map(p=>({name:p.name,role:p.role,alive:p.alive}))});emitRoom(r)}
function resetNight(r){for(const p of r.players.values())p.nightDone=false;r.night={mafia:new Map(),save:null,check:new Map()}}
function resolveNight(r){if(!r.started||r.phase!=="night")return;clearTimer(r);const counts={};for(const id of r.night.mafia.values())counts[id]=(counts[id]||0)+1;const target=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0],victim=target?r.players.get(target):null,saved=r.night.save?r.players.get(r.night.save):null;if(victim?.alive&&victim.id!==saved?.id){victim.alive=false;io.to(r.code).emit("game:nightResult",{type:"death",name:victim.name})}else if(victim)io.to(r.code).emit("game:nightResult",{type:"saved"});else io.to(r.code).emit("game:nightResult",{type:"quiet"});for(const [sid,tid] of r.night.check){const p=r.players.get(sid),t=r.players.get(tid);if(p?.alive&&t)io.to(sid).emit("oldman:result",{targetName:t.name,isMafia:t.role==="mafia"})}const w=winner(r);if(w)return endGame(r,w);resetNight(r);startTimer(r,"day",r.settings.day,()=>startVote(r))}
function ready(r){const ms=mafia(r),d=alive(r).find(p=>p.role==="doctor"),o=alive(r).find(p=>p.role==="oldman"&&!p.usedOldman);return ms.length&&ms.every(p=>r.night.mafia.has(p.id))&&(!d||r.night.save)&&(!o||[...r.night.check.keys()].includes(o.id))}
function startVote(r){if(r.started)r.votes.clear(),startTimer(r,"vote",r.settings.vote,()=>resolveVote(r))}
function resolveVote(r){if(!r.started||r.phase!=="vote")return;clearTimer(r);const c={};for(const id of r.votes.values())c[id]=(c[id]||0)+1;const max=Math.max(0,...Object.values(c)),w=Object.entries(c).filter(([,n])=>n===max);if(w.length===1&&max){const p=r.players.get(w[0][0]);if(p?.alive){p.alive=false;io.to(r.code).emit("game:eliminated",{name:p.name,role:p.role})}}else io.to(r.code).emit("game:notice","🗳️ تعادل أو لا توجد أصوات — لم يخرج أحد.");const x=winner(r);if(x)return endGame(r,x);resetNight(r);startTimer(r,"night",r.settings.night,()=>resolveNight(r))}
io.on("connection",s=>{
s.on("room:create",({name,maxPlayers,settings}={},cb)=>{const c=makeCode(),safe={night:Math.min(120,Math.max(10,Number(settings?.night)||DEFAULT.night)),day:Math.min(300,Math.max(20,Number(settings?.day)||DEFAULT.day)),vote:Math.min(120,Math.max(10,Number(settings?.vote)||DEFAULT.vote))},r={code:c,hostId:s.id,started:false,phase:"lobby",players:new Map(),votes:new Map(),night:{},settings:safe,maxPlayers:Math.min(MAX,Math.max(MIN,Number(maxPlayers)||8)),timer:null,timerEndsAt:null};r.players.set(s.id,{id:s.id,name:String(name||"لاعب").trim().slice(0,20)||"لاعب",alive:true});rooms.set(c,r);s.join(c);s.data.room=c;cb?.({ok:true,code:c});emitRoom(r)});
s.on("room:join",({code:c,name}={},cb)=>{const r=rooms.get(String(c||"").trim().toUpperCase()),n=String(name||"لاعب").trim().slice(0,20)||"لاعب";if(!r)return cb?.({ok:false,error:"الغرفة غير موجودة"});if(r.started)return cb?.({ok:false,error:"اللعبة بدأت بالفعل"});if(r.players.size>=r.maxPlayers)return cb?.({ok:false,error:"الغرفة ممتلئة"});if([...r.players.values()].some(p=>p.name.toLowerCase()===n.toLowerCase()))return cb?.({ok:false,error:"الاسم مستخدم بالفعل"});r.players.set(s.id,{id:s.id,name:n,alive:true});s.join(r.code);s.data.room=r.code;cb?.({ok:true,code:r.code});emitRoom(r)});
s.on("game:start",({code:c}={},cb)=>{const r=rooms.get(c);if(!r||r.hostId!==s.id)return cb?.({ok:false,error:"فقط الهوست يستطيع البدء"});if(r.players.size<MIN)return cb?.({ok:false,error:`تحتاج ${MIN} لاعبين على الأقل`});assignRoles(r.players.values());r.started=true;const ms=[...r.players.values()].filter(p=>p.role==="mafia").map(p=>({id:p.id,name:p.name}));for(const p of r.players.values())io.to(p.id).emit("game:role",{role:p.role,teammates:p.role==="mafia"?ms.filter(x=>x.id!==p.id):[]});resetNight(r);io.to(r.code).emit("game:notice","🎴 تم توزيع الأدوار — تبدأ الليلة الآن.");startTimer(r,"night",r.settings.night,()=>resolveNight(r))});
s.on("night:action",({code:c,action,targetId}={},cb)=>{const r=rooms.get(c),p=r?.players.get(s.id),t=r?.players.get(targetId);if(!r||r.phase!=="night"||!p?.alive||!t?.alive)return cb?.({ok:false,error:"حركة غير صالحة"});if(t.id===p.id&&action!=="save")return cb?.({ok:false,error:"لا يمكنك اختيار نفسك"});if(action==="kill"&&p.role!=="mafia")return cb?.({ok:false,error:"لست مافيا"});if(action==="save"&&p.role!=="doctor")return cb?.({ok:false,error:"لست الطبيب"});if(action==="check"&&(p.role!=="oldman"||p.usedOldman))return cb?.({ok:false,error:"قدرة غير متاحة"});if(action==="kill")r.night.mafia.set(p.id,t.id);if(action==="save")r.night.save=t.id;if(action==="check"){r.night.check.set(p.id,t.id);p.usedOldman=true}p.nightDone=true;cb?.({ok:true});if(ready(r))resolveNight(r)});
s.on("chat:send",({code:c,text,channel="public"}={},cb)=>{const r=rooms.get(c),p=r?.players.get(s.id),msg=String(text||"").trim().slice(0,300);if(!r||!p||!p.alive||r.phase!=="day"||!msg)return cb?.({ok:false,error:"الدردشة متاحة للأحياء أثناء النهار فقط"});if(channel==="mafia"&&p.role!=="mafia")return cb?.({ok:false});const ids=channel==="mafia"?mafia(r).map(x=>x.id):alive(r).map(x=>x.id);ids.forEach(id=>io.to(id).emit("chat:message",{name:p.name,text:msg,channel,at:Date.now()}));cb?.({ok:true})});
s.on("game:vote",({code:c,targetId}={},cb)=>{const r=rooms.get(c),p=r?.players.get(s.id),t=r?.players.get(targetId);if(!r||r.phase!=="vote"||!p?.alive||!t?.alive||p.id===t.id)return cb?.({ok:false,error:"تصويت غير صالح"});r.votes.set(s.id,t.id);io.to(r.code).emit("vote:update",{count:r.votes.size,total:alive(r).length});if(r.votes.size===alive(r).length)resolveVote(r);cb?.({ok:true})});
s.on("host:kick",({code:c,targetId}={},cb)=>{const r=rooms.get(c);if(!r||r.hostId!==s.id||targetId===s.id||r.started)return cb?.({ok:false,error:"لا يمكن الطرد أثناء اللعبة"});if(!r.players.has(targetId))return cb?.({ok:false});io.to(targetId).emit("room:kicked");io.sockets.sockets.get(targetId)?.disconnect(true);r.players.delete(targetId);emitRoom(r);cb?.({ok:true})});
s.on("game:rematch",({code:c}={},cb)=>{const r=rooms.get(c);if(!r||r.hostId!==s.id||r.phase!=="ended")return cb?.({ok:false});r.started=false;r.phase="lobby";r.votes.clear();r.timerEndsAt=null;for(const p of r.players.values()){p.alive=true;p.role=null;p.usedOldman=false}emitRoom(r);cb?.({ok:true})});
s.on("voice:signal",({code:c,to,data}={})=>{const r=rooms.get(c);if(r?.players.has(s.id)&&r.players.has(to))io.to(to).emit("voice:signal",{from:s.id,data})});
s.on("disconnect",()=>{const r=rooms.get(s.data.room);if(!r)return;r.players.delete(s.id);if(r.hostId===s.id)r.hostId=r.players.values().next().value?.id||null;if(!r.players.size){clearTimer(r);rooms.delete(r.code)}else{if(r.started&&r.phase!=="ended"){const w=winner(r);if(w)endGame(r,w)}emitRoom(r)}})
});const PORT=process.env.PORT||3000;server.listen(PORT,()=>console.log(`Mafia server on ${PORT}`));
